# Makefile

all:
	gcc create.c -o create -I/usr/local/include -L/usr/local/lib -lsqlite3 -std=c99
	gcc insert.c -o insert -I/usr/local/include -L/usr/local/lib -lsqlite3 -std=c99
	gcc select.c -o select -I/usr/local/include -L/usr/local/lib -lsqlite3 -std=c99
